export const UserStatus = Object.freeze({
  NON_LOGGED_IN: 'NON_LOGGED_IN',
  FEDERAL_PREAPPROVED: 'FEDERAL_PREAPPROVED',
  FEDERAL_REGISTERED: 'FEDERAL_REGISTERED',
  IDFC_PREAPPROVED: 'IDFC_PREAPPROVED',
  IDFC_REGISTERED: 'IDFC_REGISTERED',
  KOTAK_REGISTERED: 'KOTAK_REGISTERED',
  KOTAK_PREAPPROVED: 'KOTAK_PREAPPROVED',
});
