//apiStatus
export const apiStatus = {
  NONE: 'NONE',
  INITIATED: 'initiated',
  SUCCESS: 'success',
  ERROR: 'error',
};

export const commonActionType = {
  INIT_QUERY: 'INIT_QUERY',
  STORE_DATA: 'STORE_DATA',
  UPDATE_TEMPLATE: 'UPDATE_TEMPLATE',
  UPDATE_PAGE_KEY: 'UPDATE_PAGE_KEY',
  CLEAR_STORE: 'CLEAR_STORE',
  CHANGE_ROUTE: 'CHANGE_ROUTE',
};

export const paymentInitActionType = {
  TRANSACTION_INFO_REQUEST: 'TRANSACTION_INFO_REQUEST',
  TRANSACTION_INFO_SUCCESS: 'TRANSACTION_INFO_SUCCESS',
  TRANSACTION_INFO_ERROR: 'TRANSACTION_INFO_ERROR',
  TRANSACTION_INFO_PRE_SELECTED_SUCCESS:
    'TRANSACTION_INFO_PRE_SELECTED_SUCCESS',
  TRANSACTION_TIMEOUT_STORE: 'TRANSACTION_TIMEOUT_STORE',
  TRANSACTION_TIMEOUT_ERROR_MESSAGE: 'TRANSACTION_TIMEOUT_ERROR_MESSAGE',
  TRANSACTION_INFO_CLEAR_SELECTED_LENDER_EMI:
    'TRANSACTION_INFO_CLEAR_SELECTED_LENDER_EMI',

  //experiment-data
  TRANSACTION_VARIANT_BENEFIT_POPUP_RESPONSE:
    'TRANSACTION_VARIANT_BENEFIT_POPUP_RESPONSE',
};

export const paymentEnterMobileActionType = {
  UPDATE_TRANSACTION_MOBILE_NUMBER: 'UPDATE_TRANSACTION_MOBILE_NUMBER',
  UPDATE_TRANSACTION_MOBILE_NUMBER_ERROR:
    'UPDATE_TRANSACTION_MOBILE_NUMBER_ERROR',
};

export const lenderListActionType = {
  USER_TRANSACTION_INFO_REQUEST: 'USER_TRANSACTION_INFO_REQUEST',
  USER_TRANSACTION_INFO_SUCCESS: 'USER_TRANSACTION_INFO_SUCCESS',
  USER_TRANSACTION_INFO_ERROR: 'USER_TRANSACTION_INFO_ERROR',
  SELECT_LENDER: 'SELECT_LENDER',
};

export const paymentEmiActionType = {
  SELECT_EMI: 'SELECT_EMI',
  CLOSED_BENEFIT_MODEL: 'CLOSED_BENEFIT_MODEL',
};

export const paymentConfirmActionType = {
  //Second Factor
  INITIATE_SECOND_FACTOR_REQUEST: 'INITIATE_SECOND_FACTOR_REQUEST',
  INITIATE_SECOND_FACTOR_SUCCESS: 'INITIATE_SECOND_FACTOR_SUCCESS',
  INITIATE_SECOND_FACTOR_ERROR: 'INITIATE_SECOND_FACTOR_ERROR',
  VERIFY_SECOND_FACTOR_REQUEST: 'VERIFY_SECOND_FACTOR_REQUEST',
  VERIFY_SECOND_FACTOR_SUCCESS: 'VERIFY_SECOND_FACTOR_SUCCESS',
  VERIFY_SECOND_FACTOR_ERROR: 'VERIFY_SECOND_FACTOR_ERROR',
  FORGOT_PIN_TRANSACTION_REQUEST: 'FORGOT_PIN_TRANSACTION_REQUEST',
  FORGOT_PIN_TRANSACTION_SUCCESS: 'FORGOT_PIN_TRANSACTION_SUCCESS',
  FORGOT_PIN_TRANSACTION_ERROR: 'FORGOT_PIN_TRANSACTION_ERROR',
  //transaction
  INITIATE_TRANSACTION_REQUEST: 'INITIATE_TRANSACTION_REQUEST',
  INITIATE_TRANSACTION_SUCCESS: 'INITIATE_TRANSACTION_SUCCESS',
  INITIATE_TRANSACTION_ERROR: 'INITIATE_TRANSACTION_ERROR',
  CONFIRM_TRANSACTION_REQUEST: 'CONFIRM_TRANSACTION_REQUEST',
  CONFIRM_TRANSACTION_SUCCESS: 'CONFIRM_TRANSACTION_SUCCESS',
  CONFIRM_TRANSACTION_ERROR: 'CONFIRM_TRANSACTION_ERROR',
  RESEND_TRANSACTION_OTP_REQUEST: 'RESEND_TRANSACTION_OTP_REQUEST',
  RESEND_TRANSACTION_OTP_SUCCESS: 'RESEND_TRANSACTION_OTP_SUCCESS',
  RESEND_TRANSACTION_OTP_ERROR: 'RESEND_TRANSACTION_OTP_ERROR',
};

export const paymentCancelActionType = {
  SHOULD_INITIATE_CANCEL_TRANSACTION: 'INITIATE_CANCEL_TRANSACTION',
  REJECT_INITIATE_CANCEL_TRANSACTION: 'REJECT_INITIATE_CANCEL_TRANSACTION',
  CANCEL_TRANSACTION_REQUEST: 'CANCEL_TRANSACTION_REQUEST',
  CANCEL_TRANSACTION_SUCCESS: 'CANCEL_TRANSACTION_SUCCESS',
  CANCEL_TRANSACTION_ERROR: 'CANCEL_TRANSACTION_ERROR',
};

export const paymentHelpText = {
  DISPLAY_HELP_TEXT: 'DISPLAY_HELP_TEXT',
};

export const PAYMENT_ERROR_DATA = 'PAYMENT_ERROR_DATA';

export const registrationInitActionType = {
  INITIATE_CAMPAIGN_REQUEST: 'INITIATE_CAMPAIGN_REQUEST',
  INITIATE_CAMPAIGN_SUCCESS: 'INITIATE_CAMPAIGN_SUCCESS',
  INITIATE_CAMPAIGN_ERROR: 'INITIATE_CAMPAIGN_ERROR',
  INITIATE_ACTIVATION_DATA_REQUEST: 'INITIATE_ACTIVATION_DATA_REQUEST',
  INITIATE_ACTIVATION_DATA_SUCCESS: 'INITIATE_ACTIVATION_DATA_SUCCESS',
  INITIATE_ACTIVATION_DATA_ERROR: 'INITIATE_ACTIVATION_DATA_ERROR',
  UPDATE_ERROR_MESSAGE: 'UPDATE_ERROR_MESSAGE',
  POST_REGISTRATION_INITIATE_REQUEST: 'POST_REGISTRATION_INITIATE_REQUEST',
  POST_REGISTRATION_INITIATE_SUCCESS: 'POST_REGISTRATION_INITIATE_SUCCESS',
  POST_REGISTRATION_INITIATE_ERROR: 'POST_REGISTRATION_INITIATE_ERROR',
};

export const registrationConfirmActionType = {
  POST_REGISTRATION_CONFIRM_REQUEST: 'POST_REGISTRATION_CONFIRM_REQUEST',
  POST_REGISTRATION_CONFIRM_SUCCESS: 'POST_REGISTRATION_CONFIRM_SUCCESS',
  POST_REGISTRATION_CONFIRM_ERROR: 'POST_REGISTRATION_CONFIRM_ERROR',
  POST_PARTIAL_REGISTRATION_SEND_OTP_REQUEST:
    'POST_PARTIAL_REGISTRATION_SEND_OTP_REQUEST',
  POST_PARTIAL_REGISTRATION_SEND_OTP_SUCCESS:
    'POST_PARTIAL_REGISTRATION_SEND_OTP_SUCCESS',
  POST_PARTIAL_REGISTRATION_SEND_OTP_ERROR:
    'POST_PARTIAL_REGISTRATION_SEND_OTP_ERROR',
  PARTIAL_REGISTRATION_CONFIRM_REQUEST: 'PARTIAL_REGISTRATION_CONFIRM_REQUEST',
  PARTIAL_REGISTRATION_CONFIRM_SUCCESS: 'PARTIAL_REGISTRATION_CONFIRM_SUCCESS',
  PARTIAL_REGISTRATION_CONFIRM_ERROR: 'PARTIAL_REGISTRATION_CONFIRM_ERROR',
};

export const registrationSecondFactorType = {
  POST_INITIATE_CREDIT_LINE_REQUEST: 'POST_INITIATE_CREDIT_LINE_REQUEST',
  POST_INITIATE_CREDIT_LINE_SUCCESS: 'POST_INITIATE_CREDIT_LINE_SUCCESS',
  POST_INITIATE_CREDIT_LINE_ERROR: 'POST_INITIATE_CREDIT_LINE_ERROR',
  POST_VERIFY_CREDIT_LINE_REQUEST: 'POST_VERIFY_CREDIT_LINE_REQUEST',
  POST_VERIFY_CREDIT_LINE_SUCCESS: 'POST_VERIFY_CREDIT_LINE_SUCCESS',
  POST_VERIFY_CREDIT_LINE_ERROR: 'POST_VERIFY_CREDIT_LINE_ERROR',
  POST_ACTIVATION_PIN_REQUEST: 'POST_ACTIVATION_PIN_REQUEST',
  POST_ACTIVATION_PIN_SUCCESS: 'POST_ACTIVATION_PIN_SUCCESS',
  POST_ACTIVATION_PIN_ERROR: 'POST_ACTIVATION_PIN_ERROR',
};

export const setupPinInitActionType = {
  INITIATE_SETUP_PIN: 'INITIATE_SETUP_PIN',
};

export const setupPinSecondFactorActionType = {
  INITIATE_CREDIT_LINE: 'INITIATE_CREDIT_LINE',
};

export const changePinActionType = {
  POST_CHANGE_PIN_API_INITIATE: 'POST_CHANGE_PIN_API_INITIATE',
  POST_CHANGE_PIN_API_SUCCESS: 'POST_CHANGE_PIN_API_SUCCESS',
  POST_CHANGE_PIN_API_ERROR: 'POST_CHANGE_PIN_API_ERROR',
  CHANGE_PIN_UPDATE_ERROR_MESSAGE: 'CHANGE_PIN_UPDATE_ERROR_MESSAGE',
};

export const loginActionType = {
  UPDATE_MOBILE_NUMBER: 'UPDATE_MOBILE_NUMBER',
  INITIATE_LOGIN_REQUEST: 'INITIATE_LOGIN_REQUEST',
  INITIATE_LOGIN_SUCCESS: 'INITIATE_LOGIN_SUCCESS',
  INITIATE_LOGIN_ERROR: 'INITIATE_LOGIN_ERROR',
  RESET_ERROR_MESSAGE: 'RESET_ERROR_MESSAGE',
  VERIFY_AUTH_REQUEST: 'VERIFY_AUTH_REQUEST',
  VERIFY_AUTH_SUCCESS: 'VERIFY_AUTH_SUCCESS',
  VERIFY_AUTH_ERROR: 'VERIFY_AUTH_ERROR',
};

export const bicActionType = {
  INIT_BIC_SCREEN: 'INIT_BIC_SCREEN',
  GET_BIC_API_INITIATED: 'GET_BIC_API_INITIATED',
  GET_BIC_API_SUCCESS: 'GET_BIC_API_SUCCESS',
  GET_BIC_API_ERROR: 'GET_BIC_API_ERROR',
  UPDATE_SEARCH_TEXT: 'UPDATE_SEARCH_TEXT',
  INIT_BIC_SEARCH_SCREEN: 'INIT_BIC_SEARCH_SCREEN',
  CLICK_CATEGORY_SEE_MORE: 'CLICK_CATEGORY_SEE_MORE',
  CLICK_CATEGORY: 'CLICK_CATEGORY',
  CLICK_MERCHANT_SEE_MORE: 'CLICK_MERCHANT_SEE_MORE',
  CLICK_MERCHANT: 'CLICK_MERCHANT',
  CLICK_BRAND_SEE_MORE: 'CLICK_BRAND_SEE_MORE',
  CLICK_BRAND: 'CLICK_BRAND',
};

export const brandActionType = {
  INIT_BRAND_SCREEN_REQUEST: 'INIT_BRAND_SCREEN_REQUEST',
  INIT_BRAND_SCREEN_SUCCESS: 'INIT_BRAND_SCREEN_SUCCESS',
  INIT_BRAND_SCREEN_ERROR: 'INIT_BRAND_SCREEN_ERROR',
};

export const categoryActionType = {
  INIT_CATEGORY_SCREEN_REQUEST: 'INIT_CATEGORY_SCREEN_REQUEST',
  INIT_CATEGORY_SCREEN_SUCCESS: 'INIT_CATEGORY_SCREEN_SUCCESS',
  INIT_CATEGORY_SCREEN_ERROR: 'INIT_CATEGORY_SCREEN_ERROR',
};

export const merchantActionType = {
  INIT_MERCHANT_SCREEN_REQUEST: 'INIT_MERCHANT_SCREEN_REQUEST',
  INIT_MERCHANT_SCREEN_SUCCESS: 'INIT_MERCHANT_SCREEN_SUCCESS',
  INIT_MERCHANT_SCREEN_ERROR: 'INIT_MERCHANT_SCREEN_ERROR',
  LOAD_MORE_MERCHANT: 'LOAD_MORE_MERCHANT',
  APPLY_MERCHANT_FILTER: 'APPLY_MERCHANT_FILTER',
  CLEAR_SEARCH_TEXT: 'CLEAR_SEARCH_TEXT',
  CLOSE_FILTER: 'CLOSE_FILTER',
};

export const offerActionType = {
  OFFER_SCREEN_INITIATE: 'OFFER_SCREEN_INITIATE',
  OFFER_SCREEN_SUCCESS: 'OFFER_SCREEN_SUCCESS',
  OFFER_SCREEN_ERROR: 'OFFER_SCREEN_ERROR',
};

export const homeActionType = {
  INIT_CATEGORY_SCREEN: 'INIT_CATEGORY_SCREEN',
  INIT_BRAND_SCREEN: 'INIT_BRAND_SCREEN',
  INIT_MERCHANT_SCREEN: 'INIT_MERCHANT_SCREEN',
  TOGGLE_FILTER: 'TOGGLE_FILTER',
  INIT_FAQ_SCREEN: 'INIT_FAQ_SCREEN',
  INIT_CHANGE_PIN_SCREEN: 'INIT_CHANGE_PIN_SCREEN',
  INIT_HTB_SCREEN: 'INIT_HTB_SCREEN',
  INIT_VOUCHER_SCREEN: 'INIT_VOUCHER_SCREEN',
  INIT_LOGIN_SCREEN: 'INIT_LOGIN_SCREEN',
  INIT_TRANSACTION_HISTORY: 'INIT_TRANSACTION_HISTORY',
  SUD_API_REQUEST: 'SUD_API_REQUEST',
  SUD_API_SUCCESS: 'SUD_API_SUCCESS',
  SUD_API_ERROR: 'SUD_API_ERROR',
  SUD_STATUS_RESET: 'SUD_STATUS_RESET',
};

export const howToBuyActionType = {
  REDIRECT_HOW_TO_BUY: 'REDIRECT_HOW_TO_BUY',
  GET_HOW_TO_BUY_REQUEST: 'GET_HOW_TO_BUY_REQUEST',
  GET_HOW_TO_BUY_SUCCESS: 'GET_HOW_TO_BUY_SUCCESS',
  GET_HOW_TO_BUY_ERROR: 'GET_HOW_TO_BUY_ERROR',
};

export const headerActionType = {
  FIXED_HEADER: 'FIXED_HEADER',
  REMOVE_FIXED_HEADER: 'REMOVE_FIXED_HEADER',
};

export const ntbActionType = {
  SEND_OTP_REQUEST: 'SEND_OTP_REQUEST',
  SEND_OTP_SUCCESS: 'SEND_OTP_SUCCESS',
  SEND_OTP_FAILURE: 'SEND_OTP_FAILURE',
  VERIFY_OTP_SUCCESS: 'VERIFY_OTP_SUCCESS',
  VERIFY_OTP_FAILURE: 'VERIFY_OTP_FAILURE',
  INIT_OTP_SCREEN: 'INIT_OTP_SCREEN',
  INIT_SUD: 'INIT_SUD',
  SUD_API_SUCCESS: 'SUD_API_SUCCESS',
  SUD_API_ERROR: 'SUD_API_ERROR',
  LENDER_LIST: 'LENDER_LIST',
  LENDER_LIST_REQUEST: 'LENDER_LIST_REQUEST',
  LENDER_LIST_SUCCESS: 'LENDER_LIST_SUCCESS',
  LENDER_LIST_FAILURE: 'LENDER_LIST_FAILURE',
  INIT_LENDER_LIST_SCREEN: 'INIT_LENDER_LIST_SCREEN',
  CLOSE_OTP_OVERLAY_SCREEN: 'CLOSE_OTP_OVERLAY_SCREEN',
  OPEN_SERVICE_UNAVAILABLE_MODAL: 'OPEN_SERVICE_UNAVAILABLE_MODAL',
};

export const WIDGET_STORE_HEADER = 'WIDGET_STORE_HEADER';
export const WIDGET_STORE_MERCHANT_DATA = 'WIDGET_STORE_MERCHANT_DATA';
export const WIDGET_STORE_META_DATA = 'WIDGET_STORE_META_DATA';

export const widgetCheckEligibleActionType = {
  INIT_CHECK_ELIGIBLE_WIDGET_SCREEN: 'INIT_CHECK_ELIGIBLE_WIDGET_SCREEN',
  WIDGET_SEND_OTP_REQUEST: 'WIDGET_SEND_OTP_REQUEST',
  WIDGET_SEND_OTP_SUCCESS: 'WIDGET_SEND_OTP_SUCCESS',
  WIDGET_SEND_OTP_FAILURE: 'WIDGET_SEND_OTP_FAILURE',
  WIDGET_VERIFY_OTP_REQUEST: 'WIDGET_VERIFY_OTP_REQUEST',
  WIDGET_VERIFY_OTP_SUCCESS: 'WIDGET_VERIFY_OTP_SUCCESS',
  WIDGET_VERIFY_OTP_FAILURE: 'WIDGET_VERIFY_OTP_FAILURE',
  WIDGET_NTB_SMS_INITIATE: 'WIDGET_NTB_SMS_REQUEST_INITIATE',
  WIDGET_NTB_SMS_SUCCESS: 'WIDGET_NTB_SMS_SUCCESS',
  WIDGET_NTB_SMS_ERROR: 'WIDGET_NTB_SMS_ERROR',
};

export const aboutUsActionType = {
  INIT_ABOUT_US: 'INIT_ABOUT_US',
};

export const widgetEMIInfoActionType = {
  WIDGET_EMI_INFO_REQUEST: 'WIDGET_EMI_INFO_REQUEST',
  WIDGET_EMI_INFO_SUCCESS: 'WIDGET_EMI_INFO_SUCCESS',
  WIDGET_EMI_INFO_FAILURE: 'WIDGET_EMI_INFO_FAILURE',
  WIDGET_HOW_TO_BUY_REQUEST: 'WIDGET_HOW_TO_BUY_REQUEST',
  WIDGET_HOW_TO_BUY_SUCCESS: 'WIDGET_HOW_TO_BUY_SUCCESS',
  WIDGET_HOW_TO_BUY_FAILURE: 'WIDGET_HOW_TO_BUY_FAILURE',
};

export const ntbFaqActionType = {
  INIT_NTB_FAQ: 'INIT_NTB_FAQ',
};

export const privacyPolicyActionType = {
  INIT_PRIVACY_POLICY: 'INIT_PRIVACY_POLICY',
};

//LAYERS (model, snackbar and others)
export const SHOW_SNACKBAR = 'SHOW_SNACKBAR';
export const HIDE_SNACKBAR = 'HIDE_SNACKBAR';

export const modalActionType = {
  SHOW_MODAL: 'SHOW_MODAL',
  HIDE_MODAL: 'HIDE_MODAL',
};

//error block transaction modal
export const errorBlockTransactionDisplay = {
  DISPLAY_HELP_TEXT: 'DISPLAY_HELP_TEXT',
};
//Tracking
export const TRACKING_TRANSACTION = 'TRACKING_TRANSACTION';
